=== wowtianwen/dealzh/src/com/junhong/auth/resources/UserGroup_Role.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/UserGroup_Role"
	xmlns:tns="http://www.example.org/UserGroup_Role" elementFormDefault="qualified">

	<element name="roles">
		<complexType>
			<sequence>
				<element name="description" type="string" maxOccurs="1"></element>
				<element name="role" type="tns:RoleType" minOccurs="1"
					maxOccurs="unbounded"></element>
			</sequence>
		</complexType>
	</element>

	<complexType name="RoleType">
		<sequence>
			<element name="usergroup" type="string" maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="name" type="string"></attribute>
	</complexType>

</schema>

=== wowtianwen/dealzh/src/com/junhong/auth/resources/UserGroup_Role.xml
<?xml version="1.0" encoding="UTF-8"?>

<roles xmlns="http://www.example.org/UserGroup_Role"
	schemaLocation="http://www.example.org/UserGroup_Role UserGroup_Role.xsd">
	<description>
		Role and UserGroup mapping information.
		You may define more
		roles and user group.
		User group need to match with the one in data
		base.

		when you create a new Usergroup, you need to assign it to one of
		the these
		roles.
	</description>
	<role name="guest">
		<usergroup>GUEST</usergroup>
	</role>

	<role name="registered">
		<usergroup>REGISTERED</usergroup>
		<usergroup>CATEGORY_OWNER</usergroup>
		<usergroup>SYSADMIN</usergroup>
	</role>
	<role name="newsposter">
		<usergroup>NEWSPOSTER</usergroup>
		<usergroup>CATEGORY_OWNER</usergroup>
		<usergroup>SYSADMIN</usergroup>
	</role>

	<role name="category_owner">
		<usergroup>CATEGORY_OWNER</usergroup>
	</role>

	<role name="sysadmin">
		<usergroup>SYSADMIN</usergroup>
	</role>


</roles>
